version: "3.9"
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: playground-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=playground
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_ENGINE_SUBSTITUTION
  api:
    build:
      context: .  # root directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=root:example@tcp(mysql:3306)/playground?parseTime=true
    depends_on:
      - mysql
    entrypoint:
      [
        "/app/wait-for",
        "mysql:3306",
        "--",
        "/app/start.sh",
        "/app/playground"
      ]
    command: [ "gin" ]