// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock_app is a generated GoMock package.
package mock_app

import (
	context "context"
	app "playground/internal/app"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateUserUsecase is a mock of CreateUserUsecase interface.
type MockCreateUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUserUsecaseMockRecorder
}

// MockCreateUserUsecaseMockRecorder is the mock recorder for MockCreateUserUsecase.
type MockCreateUserUsecaseMockRecorder struct {
	mock *MockCreateUserUsecase
}

// NewMockCreateUserUsecase creates a new mock instance.
func NewMockCreateUserUsecase(ctrl *gomock.Controller) *MockCreateUserUsecase {
	mock := &MockCreateUserUsecase{ctrl: ctrl}
	mock.recorder = &MockCreateUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUserUsecase) EXPECT() *MockCreateUserUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateUserUsecase) Execute(ctx context.Context, args *app.CreateUserParams) (*app.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, args)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateUserUsecaseMockRecorder) Execute(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateUserUsecase)(nil).Execute), ctx, args)
}

// MockLoginUserUsecase is a mock of LoginUserUsecase interface.
type MockLoginUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockLoginUserUsecaseMockRecorder
}

// MockLoginUserUsecaseMockRecorder is the mock recorder for MockLoginUserUsecase.
type MockLoginUserUsecaseMockRecorder struct {
	mock *MockLoginUserUsecase
}

// NewMockLoginUserUsecase creates a new mock instance.
func NewMockLoginUserUsecase(ctrl *gomock.Controller) *MockLoginUserUsecase {
	mock := &MockLoginUserUsecase{ctrl: ctrl}
	mock.recorder = &MockLoginUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginUserUsecase) EXPECT() *MockLoginUserUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLoginUserUsecase) Execute(ctx context.Context, args *app.LoginUserParams) (*app.LoginUserOutputParams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, args)
	ret0, _ := ret[0].(*app.LoginUserOutputParams)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockLoginUserUsecaseMockRecorder) Execute(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLoginUserUsecase)(nil).Execute), ctx, args)
}

// MockRenewAccessTokenUsecase is a mock of RenewAccessTokenUsecase interface.
type MockRenewAccessTokenUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRenewAccessTokenUsecaseMockRecorder
}

// MockRenewAccessTokenUsecaseMockRecorder is the mock recorder for MockRenewAccessTokenUsecase.
type MockRenewAccessTokenUsecaseMockRecorder struct {
	mock *MockRenewAccessTokenUsecase
}

// NewMockRenewAccessTokenUsecase creates a new mock instance.
func NewMockRenewAccessTokenUsecase(ctrl *gomock.Controller) *MockRenewAccessTokenUsecase {
	mock := &MockRenewAccessTokenUsecase{ctrl: ctrl}
	mock.recorder = &MockRenewAccessTokenUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRenewAccessTokenUsecase) EXPECT() *MockRenewAccessTokenUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRenewAccessTokenUsecase) Execute(ctx context.Context, refreshToken string) (*app.RenewAccessTokenOutputParams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, refreshToken)
	ret0, _ := ret[0].(*app.RenewAccessTokenOutputParams)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRenewAccessTokenUsecaseMockRecorder) Execute(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRenewAccessTokenUsecase)(nil).Execute), ctx, refreshToken)
}

// MockUpdateUserUsecase is a mock of UpdateUserUsecase interface.
type MockUpdateUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateUserUsecaseMockRecorder
}

// MockUpdateUserUsecaseMockRecorder is the mock recorder for MockUpdateUserUsecase.
type MockUpdateUserUsecaseMockRecorder struct {
	mock *MockUpdateUserUsecase
}

// NewMockUpdateUserUsecase creates a new mock instance.
func NewMockUpdateUserUsecase(ctrl *gomock.Controller) *MockUpdateUserUsecase {
	mock := &MockUpdateUserUsecase{ctrl: ctrl}
	mock.recorder = &MockUpdateUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateUserUsecase) EXPECT() *MockUpdateUserUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateUserUsecase) Execute(ctx context.Context, args *app.UpdateUserParams) (*app.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, args)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateUserUsecaseMockRecorder) Execute(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateUserUsecase)(nil).Execute), ctx, args)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, args *app.User) (*app.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, args)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, args)
}

// CreateSession mocks base method.
func (m *MockUserRepository) CreateSession(ctx context.Context, args *app.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockUserRepositoryMockRecorder) CreateSession(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockUserRepository)(nil).CreateSession), ctx, args)
}

// CreateVerifyEmail mocks base method.
func (m *MockUserRepository) CreateVerifyEmail(ctx context.Context, args *app.VerifyEmail) (*app.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerifyEmail", ctx, args)
	ret0, _ := ret[0].(*app.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVerifyEmail indicates an expected call of CreateVerifyEmail.
func (mr *MockUserRepositoryMockRecorder) CreateVerifyEmail(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerifyEmail", reflect.TypeOf((*MockUserRepository)(nil).CreateVerifyEmail), ctx, args)
}

// Get mocks base method.
func (m *MockUserRepository) Get(ctx context.Context, username string) (*app.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, username)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserRepositoryMockRecorder) Get(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserRepository)(nil).Get), ctx, username)
}

// GetSession mocks base method.
func (m *MockUserRepository) GetSession(ctx context.Context, id uuid.UUID) (*app.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, id)
	ret0, _ := ret[0].(*app.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockUserRepositoryMockRecorder) GetSession(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockUserRepository)(nil).GetSession), ctx, id)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, args *app.User) (*app.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, args)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, args)
}

// UpdateEmailVerified mocks base method.
func (m *MockUserRepository) UpdateEmailVerified(ctx context.Context, args *app.VerifyEmailParams) (*app.User, *app.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailVerified", ctx, args)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(*app.VerifyEmail)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateEmailVerified indicates an expected call of UpdateEmailVerified.
func (mr *MockUserRepositoryMockRecorder) UpdateEmailVerified(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailVerified", reflect.TypeOf((*MockUserRepository)(nil).UpdateEmailVerified), ctx, args)
}
