// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateEntry(ctx context.Context, arg CreateEntryParams) (int64, error)
	GetEntry(ctx context.Context, id int64) (*Entry, error)
}

var _ Querier = (*Queries)(nil)
